# Generated by Django 5.0.3 on 2024-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_cancer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinimage',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to='images'),
        ),
    ]
